services:
  db:
    image: postgres:latest
    restart: unless-stopped
    shm_size: 128mb
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: sir9w6%odk
      POSTGRES_USER: numerouno
      POSTGRES_DB: mediastore
