spring.application.name=api
spring.datasource.url = jdbc:postgresql://localhost:5432/mediastore
spring.datasource.username = numerouno
spring.datasource.password=sir9w6%odk
# validate == check if data structure is correct (if DB is initialized with Hibernate, use update)
spring.jpa.hibernate.ddl-auto = validate
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
debug=true
